name: Lint JSON Files

on:
 push:
    branches:
      - '*'
 pull_request:
    branches:
      - '*'

jobs:
 lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Lint JSON files
      uses: rishavs/jsonlint-action@v1
      with:
        path: '.'
        extensions: 'json'
