---
  name: Validate JSON Schemas
  
  on: # yamllint disable-line rule:truthy
    workflow_dispatch:
    pull_request:
    push:
      branches: [ "dev" ]
  
  permissions: read-all
  
  jobs:
    validate:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: "Validate manifest.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: 'manifest.json'
            schema: schemas/manifest.schema.json
            # mode: strong
  
        - name: "Validate *.config.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: '*.config.json'
            schema: schemas/config.schema.json
            # mode: strong
  
        - name: "Validate *.metaconfig.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: '*.metaconfig.json'
            schema: schemas/metaconfig.schema.json
            # mode: strong
  
        - name: "Validate *.updates.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: '*.updates.json'
            schema: schemas/updates.schema.json
            # mode: strong
  
        - name: "Validate *.ports.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: '*.ports.json'
            schema: schemas/ports.schema.json
            # mode: strong
  
        - name: "Validate *.generator.json"
          uses: cardinalby/schema-validator-action@v3
          with:
            file: '*.generator.json'
            schema: schemas/generator.schema.json
            # mode: strong