---
name: Validate JSON Schemas

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
  # push:

permissions: read-all

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Validate manifest.json"
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          send_comment: true
          clear_comments: true
          json_path_pattern: 'manifest.json$'
          json_schema: ./schemas/manifest.schema.json

      - name: "Validate *.config.json"
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          send_comment: true
          clear_comments: true
          json_path_pattern: '.*.config.json$'
          json_schema: schemas/config.schema.json

      - name: "Validate *.metaconfig.json"
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          send_comment: true
          clear_comments: true
          json_path_pattern: .*.metaconfig.json$
          json_schema: schemas/metaconfig.schema.json

      - name: "Validate *.updates.json"
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          send_comment: true
          clear_comments: true
          json_path_pattern: .*.updates.json$
          json_schema: schemas/updates.schema.json

      - name: "Validate *.ports.json"
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          send_comment: true
          clear_comments: true
          json_path_pattern: .*.ports.json$
          json_schema: schemas/ports.schema.json

      - name: "Validate *.generator.json"
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          send_comment: true
          clear_comments: true
          json_path_pattern: .*.generator.json$
          json_schema: schemas/generator.schema.json