---
  name: Validate JSON Schemas (Walbo)
  
  on: # yamllint disable-line rule:truthy
    workflow_dispatch:
    # pull_request:
    push:
      branches: [ "dev" ]
  
  permissions: read-all
  
  jobs:
    validate:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: "Validate manifest.json"
          uses: walbo/validate-json@v1.1.0
          with:
            files: 'manifest.json'
            schema: schemas/manifest.schema.json
            schema-version: draft-06
            allow-matching-properties: true
            allow-union-types: true
  
        - name: "Validate *.config.json"
          uses: walbo/validate-json@v1.1.0
          with:
            files: '*.config.json'
            schema: schemas/config.schema.json
            schema-version: draft-06
            allow-matching-properties: true
            allow-union-types: true
  
        - name: "Validate *.metaconfig.json"
          uses: walbo/validate-json@v1.1.0
          with:
            files: '*.metaconfig.json'
            schema: schemas/metaconfig.schema.json
            schema-version: draft-06
            allow-matching-properties: true
            allow-union-types: true
  
        - name: "Validate *.updates.json"
          uses: walbo/validate-json@v1.1.0
          with:
            files: '*.updates.json'
            schema: schemas/updates.schema.json
            schema-version: draft-06
            allow-matching-properties: true
            allow-union-types: true
  
        - name: "Validate *.ports.json"
          uses: walbo/validate-json@v1.1.0
          with:
            files: '*.ports.json'
            schema: schemas/ports.schema.json
            schema-version: draft-06
            allow-matching-properties: true
            allow-union-types: true
  
        - name: "Validate *.generator.json"
          uses: walbo/validate-json@v1.1.0
          with:
            files: '*.generator.json'
            schema: schemas/generator.schema.json
            schema-version: draft-06
            allow-matching-properties: true
            allow-union-types: true
            # strict: false
            # print-valid-files: false
              
              