name: Validate changed Github workflows
  
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
  push:

permissions: read-all

jobs:
  validate-github-actions-workflows:
    name: Validate GitHub Actions workflows
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with: { fetch-depth: 0 }

      - name: Check for any changed workflows
        id: check-for-changed-workflows
        uses: tj-actions/changed-files@main
        with:
          files: |
            .github/workflows/**.yml

      - name: Validate workflows
        if: steps.check-for-changed-workflows.outputs.any_changed == 'true'
        uses: dsanders11/json-schema-validate-action@main
        with:
          schema: https://json.schemastore.org/github-workflow.json
          files: .github/workflows/**.yml 