---
name: Validate JSON Schemas

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
  # push:

permissions: read-all

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Validate manifest.json"
        uses: walbo/validate-json@v1.1.0
        # uses: docker://orrosenblatt/validate-json-action:latest
        with:
          files: "manifest.json"
          schema: schemas/manifest.schema.json
          #   schema-version: draft-06
          print-valid-files: false
          fail-on-missing-schema: true
          strict: true
          allow-matching-properties: false
          allow-union-types: true

      - name: "Validate *.config.json"
        uses: walbo/validate-json@v1.1.0
        with:
          files: "*.config.json"
          schema: schemas/config.schema.json
          print-valid-files: false
          fail-on-missing-schema: true
          strict: true
          allow-matching-properties: false
          allow-union-types: true

      - name: "Validate *.metaconfig.json"
        uses: walbo/validate-json@v1.1.0
        with:
          files: "*.metaconfig.json"
          schema: schemas/metaconfig.schema.json
          print-valid-files: false
          fail-on-missing-schema: true
          strict: true
          allow-matching-properties: false
          allow-union-types: true

      - name: "Validate *.updates.json"
        uses: walbo/validate-json@v1.1.0
        with:
          files: "*.updates.json"
          schema: schemas/updates.schema.json
          print-valid-files: false
          fail-on-missing-schema: true
          strict: true
          allow-matching-properties: false
          allow-union-types: true

      - name: "Validate *.ports.json"
        uses: walbo/validate-json@v1.1.0
        with:
          files: "*.ports.json"
          schema: schemas/ports.schema.json
          print-valid-files: false
          fail-on-missing-schema: true
          strict: true
          allow-matching-properties: false
          allow-union-types: true

      - name: "Validate *.generator.json"
        uses: walbo/validate-json@v1.1.0
        with:
          files: "*.generator.json"
          schema: schemas/generator.schema.json
          print-valid-files: false
          fail-on-missing-schema: true
          strict: true
          allow-matching-properties: false
          allow-union-types: true