name: Validate `*.ports.json`
on:
  workflow_dispatch:
  push:
    paths:
      - '*.ports.json'
  pull_request:
    paths:
      - '*.ports.json'
permissions: read-all
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Pull
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Schema (walbo/validate-json)
        continue-on-error: true
        uses: walbo/validate-json@main
        with:
          files: '*.ports.json'
          schema: schemas/ports.schema.json
          schema-version: draft-07
          allow-union-types: true
          strict: false
          allow-matching-properties: false
          fail-on-missing-schema: true
          # print-valid-files: false
      - name: Schema (cardinalby/schema-validator-action)
        continue-on-error: true
        uses: cardinalby/schema-validator-action@master
        with:
          file: '*.ports.json'
          schema: schemas/ports.schema.json
          fixSchemas: true
      - name: Schema (dsanders11/json-schema-validate-action)
        continue-on-error: true
        uses: dsanders11/json-schema-validate-action@main
        with:
          files: '*.ports.json'
          schema: schemas/ports.schema.json
      - name: Schema (ammarlakis/action-ajv)
        continue-on-error: true
        uses: ammarlakis/action-ajv@master
        with:
          data: '*.ports.json'
          schema: schemas/ports.schema.json
          allErrors: true
          verbose: true
